export const icons = {
	react: "devicon-react-plain",
	javascript: "devicon-javascript-plain",
	typescript: "devicon-typescript-plain",
	html: "devicon-html5-plain",
	css: "devicon-css3-plain",
	python: "devicon-python-plain",
	swift: "devicon-swift-plain",
	mysql: "devicon-mysql-plain",
	django: "devicon-django-plain",
	java: "devicon-java-plain",
	vscode: "devicon-vscode-plain",
	intellij: "devicon-intellij-plain",
	androidstudio: "devicon-androidstudio-plain",
	git: "devicon-git-plain",
	github: "devicon-github-plain",
	gitlab: "devicon-gitlab-plain",
	trello: "devicon-trello-plain",
	figma: "devicon-figma-plain",
	adobexd: "devicon-xd-plain",
	photoshop: "devicon-photoshop-plain",
}
